---
deployment:
  tasks:
    - export DEPLOYPATH=/home/abdiadam/public_html/
    # Delete default cPanel and Sitejet junk files
    - /bin/rm -f $DEPLOYPATH/default.php $DEPLOYPATH/default.html $DEPLOYPATH/index.php
    - /bin/cp -R frontend/* $DEPLOYPATH